language: go

go:
    - 1.8
    - tip

install:
    - go get github.com/mattn/goveralls
    - go get github.com/golang/dep
    - $GOPATH/bin/dep ensure

script:
    - $GOPATH/bin/goveralls -service=travis-ci
